//#line 2 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the vfh_local_planner package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __vfh_local_planner__VFHPLANNERCONFIG_H__
#define __vfh_local_planner__VFHPLANNERCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace vfh_local_planner
{
  class VFHPlannerConfigStatics;

  class VFHPlannerConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(VFHPlannerConfig &config, const VFHPlannerConfig &max, const VFHPlannerConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const VFHPlannerConfig &config1, const VFHPlannerConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, VFHPlannerConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const VFHPlannerConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, VFHPlannerConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const VFHPlannerConfig &config) const = 0;
      virtual void getValue(const VFHPlannerConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T VFHPlannerConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T VFHPlannerConfig::* field;

      virtual void clamp(VFHPlannerConfig &config, const VFHPlannerConfig &max, const VFHPlannerConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const VFHPlannerConfig &config1, const VFHPlannerConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, VFHPlannerConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const VFHPlannerConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, VFHPlannerConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const VFHPlannerConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const VFHPlannerConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, VFHPlannerConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, VFHPlannerConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<VFHPlannerConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(VFHPlannerConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("m_safety_dist_0ms"==(*_i)->name){m_safety_dist_0ms = boost::any_cast<double>(val);}
        if("m_safety_dist_1ms"==(*_i)->name){m_safety_dist_1ms = boost::any_cast<double>(val);}
        if("m_max_speed"==(*_i)->name){m_max_speed = boost::any_cast<double>(val);}
        if("m_max_speed_narrow_opening"==(*_i)->name){m_max_speed_narrow_opening = boost::any_cast<double>(val);}
        if("m_max_speed_wide_opening"==(*_i)->name){m_max_speed_wide_opening = boost::any_cast<double>(val);}
        if("m_max_acceleration"==(*_i)->name){m_max_acceleration = boost::any_cast<double>(val);}
        if("m_min_turnrate"==(*_i)->name){m_min_turnrate = boost::any_cast<double>(val);}
        if("m_max_turnrate_0ms"==(*_i)->name){m_max_turnrate_0ms = boost::any_cast<double>(val);}
        if("m_max_turnrate_1ms"==(*_i)->name){m_max_turnrate_1ms = boost::any_cast<double>(val);}
        if("m_free_space_cutoff_0ms"==(*_i)->name){m_free_space_cutoff_0ms = boost::any_cast<double>(val);}
        if("m_free_space_cutoff_1ms"==(*_i)->name){m_free_space_cutoff_1ms = boost::any_cast<double>(val);}
        if("m_obs_cutoff_0ms"==(*_i)->name){m_obs_cutoff_0ms = boost::any_cast<double>(val);}
        if("m_obs_cutoff_1ms"==(*_i)->name){m_obs_cutoff_1ms = boost::any_cast<double>(val);}
        if("m_weight_desired_dir"==(*_i)->name){m_weight_desired_dir = boost::any_cast<double>(val);}
        if("m_weight_current_dir"==(*_i)->name){m_weight_current_dir = boost::any_cast<double>(val);}
        if("m_robot_radius"==(*_i)->name){m_robot_radius = boost::any_cast<double>(val);}
        if("restore_defaults"==(*_i)->name){restore_defaults = boost::any_cast<bool>(val);}
      }
    }

    double m_safety_dist_0ms;
double m_safety_dist_1ms;
double m_max_speed;
double m_max_speed_narrow_opening;
double m_max_speed_wide_opening;
double m_max_acceleration;
double m_min_turnrate;
double m_max_turnrate_0ms;
double m_max_turnrate_1ms;
double m_free_space_cutoff_0ms;
double m_free_space_cutoff_1ms;
double m_obs_cutoff_0ms;
double m_obs_cutoff_1ms;
double m_weight_desired_dir;
double m_weight_current_dir;
double m_robot_radius;
bool restore_defaults;

    bool state;
    std::string name;

    
}groups;



//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double m_safety_dist_0ms;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double m_safety_dist_1ms;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double m_max_speed;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double m_max_speed_narrow_opening;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double m_max_speed_wide_opening;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double m_max_acceleration;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double m_min_turnrate;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double m_max_turnrate_0ms;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double m_max_turnrate_1ms;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double m_free_space_cutoff_0ms;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double m_free_space_cutoff_1ms;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double m_obs_cutoff_0ms;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double m_obs_cutoff_1ms;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double m_weight_desired_dir;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double m_weight_current_dir;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double m_robot_radius;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      bool restore_defaults;
//#line 228 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("VFHPlannerConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const VFHPlannerConfig &__max__ = __getMax__();
      const VFHPlannerConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const VFHPlannerConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const VFHPlannerConfig &__getDefault__();
    static const VFHPlannerConfig &__getMax__();
    static const VFHPlannerConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const VFHPlannerConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void VFHPlannerConfig::ParamDescription<std::string>::clamp(VFHPlannerConfig &config, const VFHPlannerConfig &max, const VFHPlannerConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class VFHPlannerConfigStatics
  {
    friend class VFHPlannerConfig;

    VFHPlannerConfigStatics()
    {
VFHPlannerConfig::GroupDescription<VFHPlannerConfig::DEFAULT, VFHPlannerConfig> Default("Default", "", 0, 0, true, &VFHPlannerConfig::groups);
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.m_safety_dist_0ms = -std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.m_safety_dist_0ms = std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.m_safety_dist_0ms = 100.0;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_safety_dist_0ms", "double", 0, "The minimum distance the robot is allowed to get to obstacles when stopped", "", &VFHPlannerConfig::m_safety_dist_0ms)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_safety_dist_0ms", "double", 0, "The minimum distance the robot is allowed to get to obstacles when stopped", "", &VFHPlannerConfig::m_safety_dist_0ms)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.m_safety_dist_1ms = -std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.m_safety_dist_1ms = std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.m_safety_dist_1ms = 100.0;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_safety_dist_1ms", "double", 0, "The minimum distance the robot is allowed to get to obstacles when stopped", "", &VFHPlannerConfig::m_safety_dist_1ms)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_safety_dist_1ms", "double", 0, "The minimum distance the robot is allowed to get to obstacles when stopped", "", &VFHPlannerConfig::m_safety_dist_1ms)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.m_max_speed = -std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.m_max_speed = std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.m_max_speed = 200.0;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_max_speed", "double", 0, "The maximum allowable speed of the robot", "", &VFHPlannerConfig::m_max_speed)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_max_speed", "double", 0, "The maximum allowable speed of the robot", "", &VFHPlannerConfig::m_max_speed)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.m_max_speed_narrow_opening = -std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.m_max_speed_narrow_opening = std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.m_max_speed_narrow_opening = 200.0;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_max_speed_narrow_opening", "double", 0, "The maximum allowable speed of the robot through a narrow opening", "", &VFHPlannerConfig::m_max_speed_narrow_opening)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_max_speed_narrow_opening", "double", 0, "The maximum allowable speed of the robot through a narrow opening", "", &VFHPlannerConfig::m_max_speed_narrow_opening)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.m_max_speed_wide_opening = -std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.m_max_speed_wide_opening = std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.m_max_speed_wide_opening = 300.0;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_max_speed_wide_opening", "double", 0, "The maximum allowable speed of the robot through a wide opening", "", &VFHPlannerConfig::m_max_speed_wide_opening)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_max_speed_wide_opening", "double", 0, "The maximum allowable speed of the robot through a wide opening", "", &VFHPlannerConfig::m_max_speed_wide_opening)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.m_max_acceleration = -std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.m_max_acceleration = std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.m_max_acceleration = 200.0;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_max_acceleration", "double", 0, "The maximum allowable acceleration of the robot.", "", &VFHPlannerConfig::m_max_acceleration)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_max_acceleration", "double", 0, "The maximum allowable acceleration of the robot.", "", &VFHPlannerConfig::m_max_acceleration)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.m_min_turnrate = -std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.m_min_turnrate = std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.m_min_turnrate = 40.0;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_min_turnrate", "double", 0, "The minimum allowable turnrate of the robot.", "", &VFHPlannerConfig::m_min_turnrate)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_min_turnrate", "double", 0, "The minimum allowable turnrate of the robot.", "", &VFHPlannerConfig::m_min_turnrate)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.m_max_turnrate_0ms = -std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.m_max_turnrate_0ms = std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.m_max_turnrate_0ms = 40.0;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_max_turnrate_0ms", "double", 0, "The maximum allowable turnrate of the robot when stopped.", "", &VFHPlannerConfig::m_max_turnrate_0ms)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_max_turnrate_0ms", "double", 0, "The maximum allowable turnrate of the robot when stopped.", "", &VFHPlannerConfig::m_max_turnrate_0ms)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.m_max_turnrate_1ms = -std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.m_max_turnrate_1ms = std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.m_max_turnrate_1ms = 40.0;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_max_turnrate_1ms", "double", 0, "The maximum allowable turnrate of the robot when travelling 1 m/s.", "", &VFHPlannerConfig::m_max_turnrate_1ms)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_max_turnrate_1ms", "double", 0, "The maximum allowable turnrate of the robot when travelling 1 m/s.", "", &VFHPlannerConfig::m_max_turnrate_1ms)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.m_free_space_cutoff_0ms = -std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.m_free_space_cutoff_0ms = std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.m_free_space_cutoff_0ms = 2000000.0;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_free_space_cutoff_0ms", "double", 0, "The higher the value, the closer the robot will get to obstacles before avoiding (while stopped).", "", &VFHPlannerConfig::m_free_space_cutoff_0ms)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_free_space_cutoff_0ms", "double", 0, "The higher the value, the closer the robot will get to obstacles before avoiding (while stopped).", "", &VFHPlannerConfig::m_free_space_cutoff_0ms)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.m_free_space_cutoff_1ms = -std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.m_free_space_cutoff_1ms = std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.m_free_space_cutoff_1ms = 2000000.0;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_free_space_cutoff_1ms", "double", 0, "The higher the value, the closer the robot will get to obstacles before avoiding (when travelling 1 m/s.).", "", &VFHPlannerConfig::m_free_space_cutoff_1ms)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_free_space_cutoff_1ms", "double", 0, "The higher the value, the closer the robot will get to obstacles before avoiding (when travelling 1 m/s.).", "", &VFHPlannerConfig::m_free_space_cutoff_1ms)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.m_obs_cutoff_0ms = -std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.m_obs_cutoff_0ms = std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.m_obs_cutoff_0ms = 4000000.0;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_obs_cutoff_0ms", "double", 0, "histogram threshold", "", &VFHPlannerConfig::m_obs_cutoff_0ms)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_obs_cutoff_0ms", "double", 0, "histogram threshold", "", &VFHPlannerConfig::m_obs_cutoff_0ms)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.m_obs_cutoff_1ms = -std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.m_obs_cutoff_1ms = std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.m_obs_cutoff_1ms = 4000000.0;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_obs_cutoff_1ms", "double", 0, "histogram threshold", "", &VFHPlannerConfig::m_obs_cutoff_1ms)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_obs_cutoff_1ms", "double", 0, "histogram threshold", "", &VFHPlannerConfig::m_obs_cutoff_1ms)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.m_weight_desired_dir = -std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.m_weight_desired_dir = std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.m_weight_desired_dir = 5.0;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_weight_desired_dir", "double", 0, "Bias for the robot to turn to move toward goal position.", "", &VFHPlannerConfig::m_weight_desired_dir)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_weight_desired_dir", "double", 0, "Bias for the robot to turn to move toward goal position.", "", &VFHPlannerConfig::m_weight_desired_dir)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.m_weight_current_dir = -std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.m_weight_current_dir = std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.m_weight_current_dir = 1.0;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_weight_current_dir", "double", 0, "Bias for the robot to continue moving in current direction of travel", "", &VFHPlannerConfig::m_weight_current_dir)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_weight_current_dir", "double", 0, "Bias for the robot to continue moving in current direction of travel", "", &VFHPlannerConfig::m_weight_current_dir)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.m_robot_radius = -std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.m_robot_radius = std::numeric_limits<double>::infinity();
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.m_robot_radius = 0;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_robot_radius", "double", 0, "robot radius, 300", "", &VFHPlannerConfig::m_robot_radius)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<double>("m_robot_radius", "double", 0, "robot radius, 300", "", &VFHPlannerConfig::m_robot_radius)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.restore_defaults = 0;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.restore_defaults = 1;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.restore_defaults = 0;
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<bool>("restore_defaults", "bool", 0, "Retore to the default configuration", "", &VFHPlannerConfig::restore_defaults)));
//#line 274 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(VFHPlannerConfig::AbstractParamDescriptionConstPtr(new VFHPlannerConfig::ParamDescription<bool>("restore_defaults", "bool", 0, "Retore to the default configuration", "", &VFHPlannerConfig::restore_defaults)));
//#line 246 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 246 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(VFHPlannerConfig::AbstractGroupDescriptionConstPtr(new VFHPlannerConfig::GroupDescription<VFHPlannerConfig::DEFAULT, VFHPlannerConfig>(Default)));
//#line 366 "/home/nlimpert/dev/pre_ws/src/dynamic_reconfigure/templates/ConfigType.h.template"

      for (std::vector<VFHPlannerConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<VFHPlannerConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<VFHPlannerConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    VFHPlannerConfig __max__;
    VFHPlannerConfig __min__;
    VFHPlannerConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const VFHPlannerConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static VFHPlannerConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &VFHPlannerConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const VFHPlannerConfig &VFHPlannerConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const VFHPlannerConfig &VFHPlannerConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const VFHPlannerConfig &VFHPlannerConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<VFHPlannerConfig::AbstractParamDescriptionConstPtr> &VFHPlannerConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<VFHPlannerConfig::AbstractGroupDescriptionConstPtr> &VFHPlannerConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const VFHPlannerConfigStatics *VFHPlannerConfig::__get_statics__()
  {
    const static VFHPlannerConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = VFHPlannerConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __VFHPLANNERRECONFIGURATOR_H__
